[package]
name = "wincompatlib"
version = "0.6.1"
description = "Set of interfaces to run windows applications on unix-like systems using Wine"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "MIT"
edition = "2021"

[dev-dependencies]
serial_test = "2.0.0"

[features]
dxvk = []

wine-bundles = []
wine-proton = ["wine-bundles"]

winetricks = []

all = ["dxvk", "wine-bundles", "wine-proton", "winetricks"]

# Used for test purposes
# default = ["all"]
