[package]
name = "wincompatlib"
version = "0.2.2"
description = "Set of interfaces to run windows applications on unix-like systems using Wine"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "MIT"
edition = "2021"

[dev-dependencies]
serial_test = "1.0.0"

[dependencies]
derive_builder = { version = "0.12.0", optional = true }

[features]
default = ["dxvk"]
dxvk = ["dep:derive_builder"]
