[package]
name = "wincompatlib"
version = "0.1.2"
description = "Set of interfaces to run windows applications on unix-like systems using Wine"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "MIT"
edition = "2021"

[dev-dependencies]
serial_test = "0.9.0"

[dependencies]
regex = { version = "1.6.0", optional = true }

[features]
dxvk = ["dep:regex"]
